services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb/data
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1m30s
      timeout: 30s
      retries: 5
  auction-svc:
    image: hengsomnang/auction-svc:latest
    build:
      context: .
      dockerfile: ./src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AuctionDb;Username=postgres;Password=postgrespw
      - IdentityServerURL=http://identity-svc
      - BunnyCdn__StorageZoneName=hengsomnang
      - BunnyCdn__AccessKey=72c7fa5b-cc98-466d-841989d51269-85b2-4641
      - BunnyCdn__RegionUrl=https://sg.storage.bunnycdn.com
      - BunnyCdn__CdnBaseUrl=https://techhl.b-cdn.net
    ports:
      - 7001:80
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  search-svc:
    image: hengsomnang/search-svc:latest
    build:
      context: .
      dockerfile: ./src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDBConnection=mongodb://mongoadmin:mongopw@mongo
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      rabbitmq:
        condition: service_started
      mongo:
        condition: service_healthy
  identity-svc:
    image: hengsomnang/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=IdentityDb;Username=postgres;Password=postgrespw
    ports:
      - 5001:80
    depends_on:
      postgres:
        condition: service_healthy
  gateway-svc:
    image: hengsomnang/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    ports:
      - 6001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - IdentityServerURL=http://identity-svc
volumes:
  postgres_data:
  mongo_data:
